<?php

class MenusTableSeeder extends Seeder {

	/**
	 * Auto generated seed file
	 *
	 * @return void
	 */
	public function run()
	{
		\DB::table('menus')->delete();
        
		\DB::table('menus')->insert(array (
			0 => 
			array (
				'id' => 1,
				'name' => 'Dashboard',
				'icon_class' => 'icon-home',
				'link' => 'admin',
				'parent_id' => 0,
				'type' => 'backend',
				'group' => '',
				'order_no' => 1,
				'level' => 1,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-04-29 02:28:36',
				'updated_at' => '2015-06-16 20:18:11',
			),
			1 => 
			array (
				'id' => 2,
				'name' => 'Menu',
				'icon_class' => 'icon-list',
				'link' => 'admin/menus',
				'parent_id' => 0,
				'type' => 'backend',
				'group' => '',
				'order_no' => 7,
				'level' => 1,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-04-29 02:35:02',
				'updated_at' => '2015-06-16 20:18:11',
			),
			2 => 
			array (
				'id' => 3,
				'name' => 'Admin',
				'icon_class' => 'icon-users',
				'link' => 'admin/admins',
				'parent_id' => 12,
				'type' => 'backend',
				'group' => '',
				'order_no' => 2,
				'level' => 2,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-04-29 02:36:11',
				'updated_at' => '2015-06-16 20:18:11',
			),
			3 => 
			array (
				'id' => 4,
				'name' => 'Role',
				'icon_class' => 'icon-user-following',
				'link' => 'admin/roles',
				'parent_id' => 12,
				'type' => 'backend',
				'group' => '',
				'order_no' => 3,
				'level' => 2,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-04-29 02:36:37',
				'updated_at' => '2015-06-16 20:18:11',
			),
			4 => 
			array (
				'id' => 5,
				'name' => 'Banner',
				'icon_class' => 'icon-screen-tablet',
				'link' => 'admin/banners',
				'parent_id' => 11,
				'type' => 'backend',
				'group' => '',
				'order_no' => 1,
				'level' => 2,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-04-29 02:36:59',
				'updated_at' => '2015-06-16 20:18:11',
			),
			5 => 
			array (
				'id' => 6,
				'name' => 'Configure',
				'icon_class' => 'icon-settings',
				'link' => 'admin/configures',
				'parent_id' => 12,
				'type' => 'backend',
				'group' => '',
				'order_no' => 1,
				'level' => 2,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-04-29 02:37:50',
				'updated_at' => '2015-06-16 20:18:11',
			),
			6 => 
			array (
				'id' => 7,
				'name' => 'Image',
				'icon_class' => 'icon-frame',
				'link' => 'admin/images',
				'parent_id' => 0,
				'type' => 'backend',
				'group' => '',
				'order_no' => 2,
				'level' => 1,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-05-04 23:52:45',
				'updated_at' => '2015-06-16 20:18:11',
			),
			7 => 
			array (
				'id' => 8,
				'name' => 'Type',
				'icon_class' => 'icon-layers',
				'link' => 'admin/types',
				'parent_id' => 11,
				'type' => 'backend',
				'group' => '',
				'order_no' => 2,
				'level' => 2,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-05-11 03:55:45',
				'updated_at' => '2015-06-16 20:18:11',
			),
			8 => 
			array (
				'id' => 9,
				'name' => 'Category',
				'icon_class' => 'icon-grid',
				'link' => 'admin/categories',
				'parent_id' => 11,
				'type' => 'backend',
				'group' => '',
				'order_no' => 3,
				'level' => 2,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-05-11 03:56:12',
				'updated_at' => '2015-06-16 20:18:11',
			),
			9 => 
			array (
				'id' => 10,
				'name' => 'Collection',
				'icon_class' => 'icon-bar-chart',
				'link' => 'admin/collections',
				'parent_id' => 0,
				'type' => 'backend',
				'group' => '',
				'order_no' => 3,
				'level' => 1,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-05-11 03:56:54',
				'updated_at' => '2015-06-16 20:18:11',
			),
			10 => 
			array (
				'id' => 11,
				'name' => 'Image Group',
				'icon_class' => 'icon-picture',
				'link' => '',
				'parent_id' => 0,
				'type' => 'backend',
				'group' => '',
				'order_no' => 4,
				'level' => 1,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-05-11 03:57:15',
				'updated_at' => '2015-06-16 20:18:11',
			),
			11 => 
			array (
				'id' => 12,
				'name' => 'Admin System',
				'icon_class' => 'icon-shield',
				'link' => '',
				'parent_id' => 0,
				'type' => 'backend',
				'group' => '',
				'order_no' => 8,
				'level' => 1,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-06-16 03:16:19',
				'updated_at' => '2015-06-16 20:18:11',
			),
			12 => 
			array (
				'id' => 13,
				'name' => 'Products',
				'icon_class' => 'icon-drawer',
				'link' => 'admin/products',
				'parent_id' => 0,
				'type' => 'backend',
				'group' => '',
				'order_no' => 5,
				'level' => 1,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-06-16 03:23:22',
				'updated_at' => '2015-06-16 20:18:11',
			),
			13 => 
			array (
				'id' => 14,
				'name' => 'Product group',
				'icon_class' => 'icon-drawer',
				'link' => '',
				'parent_id' => 0,
				'type' => 'backend',
				'group' => '',
				'order_no' => 6,
				'level' => 1,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-06-16 20:17:25',
				'updated_at' => '2015-06-16 20:18:11',
			),
			14 => 
			array (
				'id' => 15,
				'name' => 'Options',
				'icon_class' => 'icon-check',
				'link' => 'admin/product-option-groups',
				'parent_id' => 14,
				'type' => 'backend',
				'group' => '',
				'order_no' => 1,
				'level' => 2,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-06-16 20:19:23',
				'updated_at' => '2015-06-16 20:19:23',
			),
			15 => 
			array (
				'id' => 16,
				'name' => 'Option items',
				'icon_class' => 'icon-check',
				'link' => 'admin/product-options',
				'parent_id' => 14,
				'type' => 'backend',
				'group' => '',
				'order_no' => 2,
				'level' => 2,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-06-16 20:20:01',
				'updated_at' => '2015-06-16 20:20:01',
			),
		));
	}

}
